#ifndef __LED_H
#define __LED_H
#include "system.h"

//LED端口定义
#define LED(n)		(n?HAL_GPIO_WritePin(GPIOH,GPIO_PIN_4,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOH,GPIO_PIN_4,GPIO_PIN_RESET))
#define LED_Toggle (HAL_GPIO_TogglePin(GPIOH, GPIO_PIN_4)) //STM32 LED designed by Chen

#define DIR_FLAG_HIGH		HAL_GPIO_WritePin(GPIOI,GPIO_PIN_10,GPIO_PIN_SET)
#define DIR_FLAG_LOW		HAL_GPIO_WritePin(GPIOI,GPIO_PIN_10,GPIO_PIN_RESET)

#define FPGA_TRANS_HIGH	HAL_GPIO_WritePin(GPIOI,GPIO_PIN_11,GPIO_PIN_SET)
#define FPGA_TRANS_LOW	HAL_GPIO_WritePin(GPIOI,GPIO_PIN_11,GPIO_PIN_RESET)

#define WATCH_TRANS_HIGH	HAL_GPIO_WritePin(GPIOI,GPIO_PIN_2,GPIO_PIN_SET)
#define WATCH_TRANS_LOW  	HAL_GPIO_WritePin(GPIOI,GPIO_PIN_2,GPIO_PIN_RESET)

//Function
void LED_Init(void); //LED初始化函数
void POWER_AMP_ON_ZZ_NEW(void);
void POWER_AMP_OFF_ZZ_NEW(void);
#endif /*__LED_H*/
